### ISSUE TITLE
rails-api support

### ISSUE THREAD

**Issue by kurtisnelson** [gshaw/concise_logging#5]
If I'm using rails-api, I'd still like to be able to use this gem without it pulling in all of rails.

**Comment by gshaw** [comment]
Any ideas on what would need to change to make this happen? I haven't used rails-api.

**Comment by kurtisnelson** [comment]
It works with rails-api as is, it just drags in the whole rails gem as a
dependency. Is there a more concise dependency like Rack or ActiveSomething?

**Comment by leonelgalan** [comment]
@kurtisnelson you might be interested in #6, it removes rails and leaves activesupport as the single dependency.
