### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by shido76** [gshaw/concise_logging#7]
Your gem is amazing!
Have you coud be add timestamp for each line in log?

**Comment by gshaw** [comment]
I think you would have to modify it to do that.  We use it with PaperTrail app which automatically includes a timestamp so it isn't needed.

**Comment by choltz-i4cp** [comment]
If you add this to your environmental config file:
```
config.log_tags  = [->(request) { Time.now }]
```
You will get a timestamp in your logs.

**Comment by shido76** [comment]
Thank you choltz-i4cp. I will ty
