### ISSUE TITLE
Question/RFC - JSON Logging option

### ISSUE THREAD

**Issue by blasterpal** [gshaw/concise_logging#8]
I've created a feature that implements this and am rolling out to some apps. I need to add specs, but is this something you'd be interested in merging?

https://github.com/blasterpal/concise_logging/tree/json_format_options_adhoc_fields

**Comment by gshaw** [comment]
At this point I'm not sure.  The gem is working for what I need to do and I don't really have the bandwidth to grow it into something larger.

**Comment by blasterpal** [comment]
Thanks for replying. If you don't want to merge, I guess I'll fork and maintain and/or draw inspiration from your work and roll my own. Have a good day. I'll give credit if I use your code.
